<a href="https://colab.research.google.com/github/jainam-shah1/Machine-Learning/blob/main/linear_regression" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Linear Regression 
>by *Jainam Shah*

> Import necessary libraries for analysis, visualization and creating linear models

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

>Import training data csv and store it under `df_train` and I will use all 700 attributes for prediction.

In [ ]:
df_train = pd.read_csv('../Homework_2/concrete_strength_train.csv', index_col=False)
df_train.set_index('Batch', inplace=True)
print(df_train.shape)
df_train.head()


(700, 9)


Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
Batch                                                                 
0       148.0               175.0      0.0  171.0               2.0   
1       446.0                24.0     79.0  162.0              11.6   
2       250.0                 0.0     95.7  191.8               5.3   
3       165.0               128.5    132.1  175.1               8.1   
4       222.4                 0.0     96.7  189.3               4.5   

       Coarse Aggregate  Fine Aggregate  Age  Compressive Strength  
Batch                                                               
0                1000.0           828.0   28                 26.92  
1                 967.0           712.0    7                 52.01  
2                 948.9           857.2    3                  8.49  
3                1005.8           746.6   14                 33.09  
4                 967.1           870.3    3                 11.58

>Import test data csv and store it under `df_test` and it has 300 rows.

In [ ]:
df_test = pd.read_csv('../Homework_2/concrete_strength_test-1.csv', index_col=False)
df_test.set_index('Batch', inplace=True)
print(df_test.shape)
df_test.head()

(300, 8)


Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
Batch                                                                 
0       136.0               196.0     98.0  199.0               6.0   
1       143.8               136.3    106.2  178.1               7.5   
2       439.0               177.0      0.0  186.0              11.1   
3       190.3                 0.0    125.2  161.9               9.9   
4       339.0                 0.0      0.0  197.0               0.0   

       Coarse Aggregate  Fine Aggregate  Age  
Batch                                         
0                 847.0           783.0   28  
1                 941.5           774.3   28  
2                 884.9           707.9    3  
3                1088.1           802.6   14  
4                 968.0           781.0   14

>Importing dataset that contains the true value of the predicted varibale in this model analysis as `df_true`. Then I will convert the data into arrays similar to the predicted value. 

In [ ]:
df_true = pd.read_csv('../Homework_2/y_concrete_strength_test.csv', index_col=False)
df_true.set_index('Batch', inplace=True)
df_true

arr = df_true.to_numpy()
arr[:20]

array([[26.97],
       [26.15],
       [39.3 ],
       [22.72],
       [27.04],
       [26.05],
       [45.84],
       [55.51],
       [28.63],
       [33.27],
       [53.77],
       [19.69],
       [40.15],
       [79.3 ],
       [31.72],
       [36.15],
       [42.33],
       [52.82],
       [66.7 ],
       [ 6.47]])

>Changed name and spacing of columns in `df_train` dataset.

In [ ]:
df_train.columns = ['Cement','Blast_Furnace_Slag','Fly_Ash','Water','Superplasticizer',
              'Coarse_Aggregate','Fine_Aggregate','Age','Compressive_Strength']
df_train

Cement  Blast_Furnace_Slag  Fly_Ash  Water  Superplasticizer  \
Batch                                                                 
0       148.0               175.0      0.0  171.0               2.0   
1       446.0                24.0     79.0  162.0              11.6   
2       250.0                 0.0     95.7  191.8               5.3   
3       165.0               128.5    132.1  175.1               8.1   
4       222.4                 0.0     96.7  189.3               4.5   
...       ...                 ...      ...    ...               ...   
695     314.0               145.3    113.2  178.9               8.0   
696     393.0                 0.0      0.0  192.0               0.0   
697     500.0                 0.0      0.0  200.0               0.0   
698     288.0               192.0      0.0  192.0               0.0   
699     401.8                94.7      0.0  147.4              11.4   

       Coarse_Aggregate  Fine_Aggregate  Age  Compressive_Strength  
Batch                                                               
0                1000.0           828.0   28                 26.92  
1                 967.0           712.0    7                 52.01  
2                 948.9           857.2    3                  8.49  
3                1005.8           746.6   14                 33.09  
4                 967.1           870.3    3                 11.58  
...                 ...             ...  ...                   ...  
695               869.1           690.2   28                 46.23  
696               940.6           785.6    3                 19.20  
697              1125.0           613.0    1                 12.64  
698               932.0           717.8   28                 38.80  
699               946.8           852.1    3                 41.10  

[700 rows x 9 columns]

>Changed name and spacing of columns in `df_test` dataset.

In [ ]:
df_test.columns = ['Cement','Blast_Furnace_Slag','Fly_Ash','Water','Superplasticizer',
              'Coarse_Aggregate','Fine_Aggregate','Age']
df_test

Cement  Blast_Furnace_Slag  Fly_Ash  Water  Superplasticizer  \
Batch                                                                 
0       136.0               196.0     98.0  199.0               6.0   
1       143.8               136.3    106.2  178.1               7.5   
2       439.0               177.0      0.0  186.0              11.1   
3       190.3                 0.0    125.2  161.9               9.9   
4       339.0                 0.0      0.0  197.0               0.0   
...       ...                 ...      ...    ...               ...   
295     337.9               189.0      0.0  174.9               9.5   
296     318.8               212.5      0.0  155.7              14.3   
297     255.0                 0.0      0.0  192.0               0.0   
298     249.1                 0.0     98.8  158.1              12.8   
299     233.8                 0.0     94.6  197.9               4.6   

       Coarse_Aggregate  Fine_Aggregate  Age  
Batch                                         
0                 847.0           783.0   28  
1                 941.5           774.3   28  
2                 884.9           707.9    3  
3                1088.1           802.6   14  
4                 968.0           781.0   14  
...                 ...             ...  ...  
295               944.7           755.8   56  
296               852.1           880.4    3  
297               889.8           945.0    7  
298               987.8           889.0    3  
299               947.0           852.2   14  

[300 rows x 8 columns]

>Call linearRegression function and fit the data into train and test variables then print intercept and coefficients in form of w...

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df_train[['Cement','Blast_Furnace_Slag','Fly_Ash','Water','Superplasticizer',
              'Coarse_Aggregate','Fine_Aggregate','Age']], df_train['Compressive_Strength'])
w = [reg.intercept_, reg.coef_[0], reg.coef_[1], reg.coef_[2], reg.coef_[3], reg.coef_[4], reg.coef_[5], reg.coef_[6], reg.coef_[7]]
print('w_0 =', w[0], '\nw_1 =', w[1], '\nw_2 =', w[2], '\nw_3 =', w[3], '\nw_4 =', w[4], '\nw_5 =', w[5],'\nw_6 =', w[6], '\nw_7 =', w[7], '\nw_8 =', w[8])


w_0 = -21.257356684799035 
w_1 = 0.12137998687621716 
w_2 = 0.10703156220314446 
w_3 = 0.09031757773240537 
w_4 = -0.17228536137653988 
w_5 = 0.2139221261135758 
w_6 = 0.019803933706534174 
w_7 = 0.02003485210687323 
w_8 = 0.11651740629379011


**Statsmodels**

In [ ]:
import statsmodels.formula.api as smf
sm = smf.ols(formula='Compressive_Strength ~ Cement + Blast_Furnace_Slag + Fly_Ash + Water + Superplasticizer + Coarse_Aggregate + Fine_Aggregate + Age',data = df_train).fit()
sm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                             
================================================================================
Dep. Variable:     Compressive_Strength   R-squared:                       0.632
Model:                              OLS   Adj. R-squared:                  0.628
Method:                   Least Squares   F-statistic:                     148.4
Date:                  Mon, 14 Nov 2022   Prob (F-statistic):          1.60e-144
Time:                          12:44:20   Log-Likelihood:                -2619.7
No. Observations:                   700   AIC:                             5257.
Df Residuals:                       691   BIC:                             5298.
Df Model:                             8                                         
Covariance Type:              nonrobust                                         
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            -21.2574     33.588     -0.633      0.527     -87.205      44.690
Cement                 0.1214      0.010     11.567      0.000       0.101       0.142
Blast_Furnace_Slag     0.1070      0.012      8.575      0.000       0.083       0.132
Fly_Ash                0.0903      0.015      5.917      0.000       0.060       0.120
Water                 -0.1723      0.051     -3.352      0.001      -0.273      -0.071
Superplasticizer       0.2139      0.113      1.891      0.059      -0.008       0.436
Coarse_Aggregate       0.0198      0.012      1.656      0.098      -0.004       0.043
Fine_Aggregate         0.0200      0.013      1.522      0.129      -0.006       0.046
Age                    0.1165      0.007     17.820      0.000       0.104       0.129
==============================================================================
Omnibus:                        2.533   Durbin-Watson:                   2.081
Prob(Omnibus):                  0.282   Jarque-Bera (JB):                2.431
Skew:                          -0.143   Prob(JB):                        0.297
Kurtosis:                       3.039   Cond. No.                     1.12e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

>According to **t** value we can denote that 

>Which ingredient affects the strength most? - **Cement**<br>

>Which ingredient affects the strength least? - **Fine Aggregate**

After we predict the intercept and individual coefficients, we can further predict **Compressive_Strength** using our `df_test` dataset and then print the result in an array form.

In [ ]:
y_bar =  reg.predict(df_test).reshape(-1,1)
y_bar[:20]
#df_x=pd.DataFrame({'cities':y_bar}, index=[0])
#print(df_x)


array([[27.80208461],
       [28.71848414],
       [53.35922741],
       [26.63372085],
       [22.39891369],
       [30.550675  ],
       [37.48651565],
       [40.98809642],
       [16.60183889],
       [26.99120512],
       [36.1816663 ],
       [18.42958993],
       [35.6532498 ],
       [61.50983375],
       [30.46336596],
       [60.72258558],
       [25.22695894],
       [43.58887455],
       [64.84311719],
       [11.21556427]])

>**r2_score**:- <br><br>
$r2 = 1 – (SSres  /SSmean )$<br>
 $r2 = 1 - (original values(y) - predicted values(y^))^2$

In [ ]:
from sklearn.metrics import r2_score


In [ ]:
accuracy = reg.score(df_test, df_true['Compressive Strength'])*100
print('Accuracy is',round(accuracy,2),'%')


Accuracy is 56.22 %


Hence after we concatenate both the arrays and print them as one.

In [ ]:
con = np.concatenate((arr, y_bar), axis=1)
print(con[:20])

[[26.97       27.80208461]
 [26.15       28.71848414]
 [39.3        53.35922741]
 [22.72       26.63372085]
 [27.04       22.39891369]
 [26.05       30.550675  ]
 [45.84       37.48651565]
 [55.51       40.98809642]
 [28.63       16.60183889]
 [33.27       26.99120512]
 [53.77       36.1816663 ]
 [19.69       18.42958993]
 [40.15       35.6532498 ]
 [79.3        61.50983375]
 [31.72       30.46336596]
 [36.15       60.72258558]
 [42.33       25.22695894]
 [52.82       43.58887455]
 [66.7        64.84311719]
 [ 6.47       11.21556427]]


> Create a new dataframe `pred_df` to store both the Actual and Predicted value from our linear regression model.

In [ ]:
pred_df=pd.DataFrame({'Actual Value':con[:,0],'Predicted Value':con[:,1],'Difference':con[:,0]-con[:,1]})
pred_df.head()

Actual Value  Predicted Value  Difference
0         26.97        27.802085   -0.832085
1         26.15        28.718484   -2.568484
2         39.30        53.359227  -14.059227
3         22.72        26.633721   -3.913721
4         27.04        22.398914    4.641086

In [ ]:
accuracy = r2_score(pred_df['Predicted Value'], pred_df['Actual Value'])*100
print('Accuracy is',round(accuracy,2),'%')

Accuracy is 30.91 %


>Plot a scatter a graph to show the correlation between the actual and predicted value and as you can it shows linear correlation.

In [ ]:
plt.figure(figsize = (12,10))
sns.regplot(x= "Predicted Value", y= "Actual Value", data = pred_df, fit_reg=True, scatter_kws = {'color': 'skyblue'}, line_kws = {'color': '#CCCC00'},marker='*');
plt.title('Predicted Value(y^) vs Actual Value(y)', fontsize = 20)

plt.show()
